apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: longhorn-pvc
  name: data-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
  storageClassName: longhorn-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: longhorn-pvc
  name: log-volume-claim-2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn-1