import os

SIIBRA_TOOLBOX_VIEWER_PLUGIN_STATIC_DIR = os.getenv("SIIBRA_TOOLBOX_VIEWER_PLUGIN_STATIC_DIR")

HBP_GITLAB_HOST = os.getenv("HBP_GITLAB_HOST")
HBP_GITLAB_TOKEN = os.getenv("HBP_GITLAB_TOKEN")
HBP_GITLAB_PROJECT_ID = os.getenv("HBP_GITLAB_PROJECT_ID")

CHANNEL = os.getenv("SIIBRA_JURGEX_CELERY_CHANNEL", "siibra_jugex_http")